language: node_js

node_js:
  - 6.11.5
  - 8
  - 9

script:
- npm run lint:fix
- npm run test:cov
- npm run build

sudo: false

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    node: '9'

after_success:
- bash <(curl -s https://codecov.io/bash)
