language: node_js

node_js:
- '6'

script:
- npm run lint:fix
- npm run test:cov
- npm run build

sudo: false

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key:
    secure: $NPM_KEY
    tags: true
    repo: nmccready/tsheets-sdk

# after_success:
# - bash <(curl -s https://codecov.io/bash)
